version: "3"

services:

  postgres:
    image: postgres:12
    hostname: postgres
    ports:
      - "5432:5432"
    volumes: 
      - ./db/data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    networks:
      - awesome

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80" # 80 - port in container, 8080 - port on a machine
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - awesome

  bot:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - awesome

volumes:
    pgadmin-data:

networks:
    awesome:
        driver: bridge